language: android

jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-armeabi-v7a-android-17

image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.0"
  ANDROID_SDK_TOOLS_REV: "3859397"  # "26.0.1"
  ANDROID_CMAKE_REV: "3.6.3155560"
  GIT_SUBMODULE_STRATEGY: recursive # Remove if you don't have to clone submodules

before_script:
  - mkdir -p $HOME/.android # For sdkmanager configs
  - echo 'count=0' > $HOME/.android/repositories.cfg # Avoid warning
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS_REV}.zip
  - mkdir -p $PWD/android-sdk-linux
  - unzip -qq android-sdk.zip -d $PWD/android-sdk-linux
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle # Remove if you don't need NDK
  - export PATH=$PATH:$ANDROID_HOME/platform-tools/:$ANDROID_NDK_HOME
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager --update
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'tools'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platform-tools'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'build-tools;'$ANDROID_BUILD_TOOLS
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-'$ANDROID_COMPILE_SDK
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;android;m2repository'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;google_play_services'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;m2repository'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'cmake;'$ANDROID_CMAKE_REV
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'ndk-bundle' # Remove if you don't need NDK
  - chmod +x ./gradlew

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_TAG}_${CI_COMMIT_SHA}"
    paths:
    - app/build/outputs/

notifications:
    slack: stefans:guQ4vRvf0Tyi2iDilb1rgQAj

cache:
  apt: true
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - ${TRAVIS_BUILD_DIR}/android-sdk/extras/
