language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ANDROID_TARGET=android-25
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOL_VERSION=25.0.3
    - ADB_INSTALL_TIMEOUT=8

licenses:
    - '.+'

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOL_VERSION

    # The SDK version used to compile your project
    - $ANDROID_TARGET

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - extra-android-support # because I'm using support library
    # - sys-img-x86-$ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_API_LEVEL
    # - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL

install: true

before_script:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - chmod +x gradlew

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
  # Make sure the emulator has started before running tests
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./wait_for_emulator
  - adb shell input keyevent 82 &

script:
  # - ./gradlew assembleRelease --stacktrace --no-daemon
  - ./gradlew cC #Connected Check

notifications:
    slack: stefans:guQ4vRvf0Tyi2iDilb1rgQAj

cache:
  apt: true
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - ${TRAVIS_BUILD_DIR}/android-sdk/extras/
